unbind C-a
set -g prefix C-a
bind C-a send-prefix

set -g default-terminal "${TERM}"
set-option -a terminal-features 'xterm-256color:RGB'
setw -g mode-keys vi
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g set-clipboard on

bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt

# Start windows and panes at 1 and not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @plugin 'dracula/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fcsonline/tmux-thumbs'

set -g @dracula-plugins "git"
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

# Create a binding to disable Ctrl+j and Ctrl+k navigation
bind-key M-d \
  unbind-key -n C-j \;\
  unbind-key -n C-k \;\
  display-message "Disabled Ctrl+j and Ctrl+k navigation"

# Create a binding to re-enable Ctrl+j and Ctrl+k navigation
bind-key M-e \
  bind-key -n C-j select-pane -D \;\
  bind-key -n C-k select-pane -U \;\
  display-message "Enabled Ctrl+j and Ctrl+k navigation"


run '~/.tmux/plugins/tpm/tpm'

